name: Flutter Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
            architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        working-directory: ./example
        run: flutter build web --dart-define=GIPHY_API_KEY=${{ secrets.GIPHY_API_KEY }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
